import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"

export const metadata = {
  title: "Terms of Service",
  description: "Ollie terms of service. Read our usage rules and disclaimers.",
  alternates: { canonical: "/terms" },
}

export default function TermsPage() {
  return (
    <main className="relative min-h-screen bg-black">
      <Nav />
      <div className="max-w-3xl mx-auto px-6 pt-32 pb-20">
        <h1 className="text-4xl font-black text-white mb-2 tracking-tight">Terms of Service</h1>
        <p className="text-white/30 text-sm mb-12">Last updated: June 2026</p>

        <div className="prose prose-invert max-w-none space-y-10 text-white/60 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Ollie (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>Ollie is an AI-powered celebrity face matching tool for entertainment purposes. You upload a photo and the Service returns a list of celebrities whose facial features most closely resemble yours. Results are generated by machine learning and are approximate — they are not scientific, medical, or legally definitive assessments.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Upload images of individuals without their consent</li>
              <li>Use the Service to harass, stalk, or identify private individuals</li>
              <li>Use the Service for surveillance, law enforcement, or facial recognition profiling</li>
              <li>Attempt to reverse-engineer or scrape the Service</li>
              <li>Upload illegal content, including CSAM</li>
              <li>Use the Service in any way that violates applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Age Restriction</h2>
            <p>You must be at least 13 years old to use Ollie. By using the Service you confirm you meet this requirement.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Intellectual Property</h2>
            <p>All content, AI models, code, and design of Ollie are owned by or licensed to us. You may not reproduce, distribute, or create derivative works without written permission. Celebrity images used for matching are sourced from publicly available datasets under their respective licences.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We do not warrant that results will be accurate, that the Service will be uninterrupted, or that it is error-free. Celebrity similarity results are for entertainment only.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, Ollie and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data or reputation.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Celebrity Disclaimer</h2>
            <p>Ollie is not affiliated with, endorsed by, or connected to any celebrity, entertainment company, or talent agency. Celebrity names and likenesses are used solely to identify public figures for entertainment comparison purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Changes will be posted on this page. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Contact</h2>
            <p>Questions about these terms? Contact us at <a href="mailto:rubixion76@gmail.com" className="text-sky-400 hover:underline">rubixion76@gmail.com</a>.</p>
          </section>

        </div>
      </div>
      <Footer />
    </main>
  )
}
